### ISSUE TITLE
Can't resubscribe through API if email was deleted or user unsubscribed

### ISSUE THREAD

**Issue by jsunsawyer** [aelvan/mailchimp-subscribe-craft#65] opened 2018-09-10 22:30 UTC
I was testing a new list with my primary email and deleted it to resubscribe and test changes. Everything looked successful on the front-end, but I never received another double opt-in email, nor did my list ever add my email back to the list of the subscribers.

After further testing, I found that unsubscribing a user also made it impossible for a user to resubscribe via the API. Changes to my single hidden field did apply to existing unsubscribed users. They just remain unsubscribed.

See:
https://stackoverflow.com/questions/36494975/can-not-re-subscribe-deleted-member
https://stackoverflow.com/questions/42159327/resubscribe-a-user-to-a-mailchimp-list-after-unsubscribe

**Comment by lealea** [comment] 2018-09-14 20:40
I am also seeing this issue.

**Comment by aelvan** [comment] 2018-09-15 16:04
Are you using the Craft 2 or 3 version of the plugin? 

And how are you deleting your email from the list? In the mailchimp admin panel, through the unsubscribe link in an email, or through the api?

**Comment by lealea** [comment] 2018-09-15 16:10
For me, it’s the Craft 2 version. For deleting, I manually remove using the MailChimp control panel which worked in the past for testing the same email. There’s 2 delete options, one that includes archive and one that is supposed to be a complete wipe. I chose the complete wipe and it still gives me an error if I try to resubscribe using that email

**Comment by jsunsawyer** [comment] 2018-09-15 17:05
I am on the Craft 3 version.

I tested both deleting and unsubscribing users from the Mailchimp admin panel. Neither would allow me to resubscribe.

I think I tried using the unsubscribe link and resubscribing as well, but can't remember. I can test it out on Monday.

**Comment by aelvan** [comment] 2018-09-15 17:28
I dived into this, but didn't emerge with a lot of solutions. :-/ 

The Craft 2 version provides a controller and service action for unsubscribing through the API. When unsubscribing using this, it's possible to re-subscribe without issues. 

If the user unsubscribes through the unsubscribe links in the mailchimp emails, or is deleted through the "Delete and archive" method in the admin CP, it's possible to re-subscribe through the API, but only by setting the new status to "pending", which triggers a new opt-in email. At the moment, the status is set to "subscribed", I'm contemplating if I should change this to "pending" or creating a config setting for this. 

If you delete a user using the "Delete and remove" method in the CP, I have not found any way to re-subscribe that user to the list using the API. The API doesn't return any information about the user when queried (so I wouldn't know that they had been deleted), and when trying to sign him up (no matter what status is used), there is an error message saying that this is an forgotten email. Using mailchimp's own signup forms to re-subscribe though, works... :( 

Craft 3 doesn't have any notion of unsubscribes atm (I added that to the Craft 2 version after porting to Craft 3). So I'll have to revisit this and add that at some point.


All of this re-subscribing stuff seems to have changed a lot lately, due to MailChimps attempts to stay compliant with privacy policies. Using the API is not compliant with GDPR atm, only subscribing through MailChimp's own forms. So I suspect that things are kind of in limbo at the moment.

If anyone want's to do some more research on how to make this work through the API, or have any suggestions, that would be much appreciated.

**Comment by masiorama** [comment] 2018-12-06 16:48
Just had the same issue on Craft 3. Are there any updates on the matter?
Atm the library is kinda not working as expected.
Thanks in advance.

**Comment by domstubbs** [comment] 2019-04-12 12:02
I ran into this on an old Craft 2 build today. The issue is that the plugin currently only sends the [status_if_new](https://github.com/aelvan/mailchimp-subscribe-craft/blob/5c51661861dc2495e0c2a97e5172d9e7f28ce65b/src/services/MailchimpSubscribeService.php#L79) value, so statuses for existing contacts will never be changed.

For my use-case (double opt-in) the fix was just to set `'status' => 'pending'` in addition to the `status_if_new` property. This ensures that any previously unsubscribed emails receive a fresh opt-in confirmation.

One catch is that resubscribing via the API [will not work for deleted contacts](https://stackoverflow.com/a/52376496/1777801). If you try that MC will return a "Forgotten Email Not Subscribed” error.

Ref [Mailchimp API docs](https://developer.mailchimp.com/documentation/mailchimp/reference/lists/members/#edit-put_lists_list_id_members_subscriber_hash), [@mailchimp tweet](https://twitter.com/mailchimp/status/718012046328074240?lang=en-gb).

**Comment by aelvan** [comment] 2019-06-28 20:45
v3.0.0 has implemented both unsubscribe, delete and permanent delete, see explanation in the docs regarding the difference. Mailchimp has also changed their default behavior a couple of times, so don't think the original issue is still valid. Closing.

**Closed by aelvan** 2019-06-28 20:45 UTC
